-- 08.관계리모델링.pdf
-- M:N 관계
/*
    다대다(M:N) 관계
    1. 현실에서 빈번히 나타나지만 주의해야 하는 관계이다.
    2. 두 테이블을 다대다 관계로 직접 연결하는 것은 불가능하다.
    3. 두 테이블을 관계 맺어 줄 별도의 테이블이 추가로 필요하다.
    4. 다대다(M:N) 관계 1개는 일다대(1:M) 관계 2개로 만들 수 있다.
*/


--테이블 삭제
DROP TABLE ENROLL_TBL;
DROP TABLE SUBJECT_TBL;
DROP TABLE STUDENT_TBL;


-- 학생 테이블 생성
CREATE TABLE STUDENT_TBL(
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(15 BYTE) NULL,
    STU_AGE NUMBER(3),
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

-- 과목 테이블 생성
CREATE TABLE SUBJECT_TBL(
    SUB_CODE VARCHAR2(1 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(10 BYTE) NULL,
    PROFESSOR VARCHAR2(15 BYTE) NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);

-- 수강신청 테이블 생성
CREATE TABLE ENROLL_TBL(
    ENR_NO NUMBER   NOT NULL,
    STU_NO VARCHAR2(5 BYTE) NOT NULL,
    SUB_CODE VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT_TBL (SUB_CODE)
);    















